Introduce Sorbet TypeChecking
brave-intl/publishers pull request #3480
Opened 2021-11-09 20:49 UTC by tsmartt

2021-11-10 00:05 UTC, porteron approved these changes

2021-11-10 13:50 UTC, thypon requested changes
- Can we exclude `rbi` from the changes? They seems autogenerated and we should not edit them anyway
- Can we split all the `# type: ignore` changes in a separated commit?

2021-11-11 18:26 UTC, tsmartt commented on Gemfile
> +gem "sorbet", group: :development
Done.

2021-11-11 18:26 UTC, tsmartt commented on Gemfile
> +gem "sorbet-rails"
Done.

2021-11-11 18:27 UTC, tsmartt commented on Gemfile
> +  gem "tapioca", require: false
Done.

2021-11-11 18:27 UTC, tsmartt commented on Gemfile
> +gem "sorbet-runtime"
Done.

2021-11-11 18:29 UTC, tsmartt commented
> Can we exclude rbi from the changes? They seems autogenerated and we should not edit them anyway
They are [meant to be vendored](https://sorbet.org/docs/rbi#a-note-about-vendoring-rbis) for explicit upgrade reasons

> Can we split all the # type: ignore changes in a separated commit?
This PR will get squashed into 1 commit when merged.

2021-11-11 18:33 UTC, thypon commented
GTG

2021-11-11 19:39 UTC, merged