We should remove the address field from the pCDN wallet if the addres…
brave-intl/publishers pull request #3926
Opened 2022-11-28 23:19 UTC by tsmartt

…s is nil

2022-11-29 17:06 UTC, OAuthBringer commented on app/jobs/cache/browser_channels/responses_for_prefix.rb
> +            gemini_address = site_banner_lookup.channel.gemini_connection&.recipient_id
@tsmartt Here as well.

2022-11-29 17:35 UTC, OAuthBringer commented
@tsmartt Why would we include the channel in the pCDN at all if it has no address?

2022-11-29 20:34 UTC, OAuthBringer requested changes
I'm not sure where the change is, but we should revert to having `address` set to empty string and not dropped as it would likely break everything.

2022-11-29 22:04 UTC, tsmartt commented on app/jobs/cache/browser_channels/responses_for_prefix.rb
> +            uphold_address = site_banner_lookup.channel.uphold_connection&.address
Resolved

2022-11-29 22:04 UTC, tsmartt commented on app/jobs/cache/browser_channels/responses_for_prefix.rb
> +            gemini_address = site_banner_lookup.channel.gemini_connection&.recipient_id
Resolved

2022-11-29 22:05 UTC, tsmartt commented
> I'm not sure where the change is, but we should revert to having `address` set to empty string and not dropped as it would likely break everything.

They are now included, but with a blank string

2022-11-30 14:02 UTC, OAuthBringer approved these changes

2022-11-30 17:41 UTC, merged