fix: add in card creation per channel to uphold connection lifecycle …
brave-intl/publishers pull request #3933
Opened 2022-12-06 15:50 UTC by jlbyrne

…methods

Addresses https://github.com/brave-intl/creators-private-issues/issues/134

2022-12-08 17:32 UTC, jlbyrne commented on app/models/uphold_connection.rb
> -      create_uphold_cards if missing_card? && success
The create uphold cards job checks to see if cards are already created.  It also exits early if there is an existing uphold connection for channel that has a card id.  No requests to uphold are made that won't need to be made.

2022-12-08 22:22 UTC, tsmartt requested changes
Thanks for tackling this!

I made a small comment about the check. 

With these dependent destroy changes, what do you think about adding tests to ensure that upon disconnect, the old cards are destroyed?

2022-12-08 22:22 UTC, tsmartt commented on app/models/uphold_connection.rb
> -      create_uphold_cards if missing_card? && success
I'd vote to keep this check in place so we don't queue unnecessary jobs

2022-12-08 22:23 UTC, jlbyrne commented
I think I added some for uphold when I made the other change, but I can add some for Gemini

2022-12-09 00:12 UTC, tsmartt approved these changes
LG2M. 

This historic code is a mess and I'll make a ticket to clean it up further. Notably, since there are 2 types of cards, something like 

```ruby
create_uphold_connection_card if missing_connection_card? && success
create_uphold_channel_cards if missing_channel_card? && success
```

can be done here.

2022-12-09 00:14 UTC, merged