Dep updates
brave-intl/publishers pull request #3989
Opened 2023-02-03 22:14 UTC by tsmartt

2023-02-03 22:43 UTC, diracdeltas commented
@tsmartt lgtm but can we get `yarn audit` added to one of the github actions jobs so it's easy to tell if there are dependency vulns? 

same with `bundler audit` or whatever the equivalent is these days for ruby

2023-02-06 20:50 UTC, diracdeltas commented on public/creators-landing/package.json
> +    "minimatch": "3.0.5"
shouldn't there be an update to yarn.lock in this directory too?

2023-02-06 20:52 UTC, diracdeltas requested changes
seems like this needs a yarn lock update in creators-landing. also please add `yarn audit` and the ruby gems equivalent (bundler audit?) to a github action so it gets flagged earlier

2023-02-08 17:49 UTC, diracdeltas approved these changes
still some audit issues (and the audit command should be fixed to run the later commands even if the first audit fails), but approving since this is an improvement.

2023-02-10 23:40 UTC, thypon commented
Why did we updated the SVGs here? Can we run the SVGO optimizer to remove spurious inkscape stuff?

2023-02-13 11:28 UTC, bcaller commented on config/environments/test.rb
> +  config.consider_all_requests_local       = true
ignore due to test environment

2023-02-13 11:39 UTC, thypon commented on config/environments/test.rb
> +  config.consider_all_requests_local       = true
We should probably add that to the `.semgrepignore` file in this repo

2023-02-16 18:00 UTC, jlbyrne approved these changes

2023-02-16 19:51 UTC, jlbyrne approved these changes

2023-02-16 19:55 UTC, merged